wheel_track:
    front: 0.52
    rear: 0.52
wheelbase: 1.38
wheel_radius:
    front: 0.325
    rear: 0.325
wheel_width:
    front: 0.13
    rear: 0.13
hub_carrier_offset:
    front: 0.148
    rear: 0.148
aabb :
    length: 2.3490
    width: 0.7000
    height: 1.1330
    center: [0., 0., 0.71650]
mass: 340.
mass_center_position: [0, 0., 0.71650]
ground_clearance: 0.15
