front_left_wheel_steering_joint: {"p": 1000.0, "i": 0.01, "d": 10.0}
front_right_wheel_steering_joint: {"p": 1000.0, "i": 0.01, "d": 10.0}
rear_left_wheel_steering_joint: {"p": 1000.0, "i": 0.01, "d": 10.0}
rear_right_wheel_steering_joint: {"p": 1000.0, "i": 0.01, "d": 10.0}
front_left_wheel_spinning_joint: {"p": 10.0, "i": 0.0, "d": 0.0}
front_right_wheel_spinning_joint: {"p": 10.0, "i": 0.0, "d": 0.0}
rear_left_wheel_spinning_joint: {"p": 10.0, "i": 0.0, "d": 0.0}
rear_right_wheel_spinning_joint: {"p": 10.0, "i": 0.0, "d": 0.0}
